#!/usr/bin/env python3
"""Build and verify PromptCraft browser runtime files from editable source files.

Editable application code lives in ``src/``. Browser-loaded files live in ``runtime/``.
The main JavaScript and CSS files are generated bundles; standalone dialogue and
Ideas Wall files are synchronized copies of their source owners.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

JS_BUNDLE_PATH = ROOT / "runtime/js/promptcraft.bundle.js"
CSS_BUNDLE_PATH = ROOT / "runtime/css/promptcraft.css"

JS_MANIFEST_PATH = ROOT / "src/js/manifest.json"


def load_js_manifest() -> tuple[tuple[Path, ...], tuple[tuple[Path, Path], ...]]:
    data = json.loads(JS_MANIFEST_PATH.read_text(encoding="utf-8"))
    bundle = tuple(Path("src/js") / value for value in data.get("bundle", []))
    standalone = tuple(
        (Path("src/js") / item["source"], Path(item["runtime"]))
        for item in data.get("standalone", [])
    )
    if not bundle:
        raise ValueError("src/js/manifest.json must define at least one bundle source.")
    return bundle, standalone


JS_SOURCES, JS_STANDALONE_FILES = load_js_manifest()

CSS_MANIFEST_PATH = ROOT / "src/css/manifest.css"


def load_css_manifest() -> tuple[Path, ...]:
    manifest = CSS_MANIFEST_PATH.read_text(encoding="utf-8")
    values = re.findall(r'@import\s+url\(["\']([^"\'?]+)', manifest)
    sources = tuple(
        (CSS_MANIFEST_PATH.parent / value).resolve().relative_to(ROOT.resolve())
        for value in values
    )
    if not sources:
        raise ValueError("src/css/manifest.css must import at least one application stylesheet.")
    if len(set(sources)) != len(sources):
        raise ValueError("src/css/manifest.css contains duplicate imports.")
    return sources


CSS_SOURCES = load_css_manifest()

STANDALONE_FILES = JS_STANDALONE_FILES + (
    (Path("src/css/pages/ideas-wall.css"), Path("runtime/css/ideas-wall.css")),
)

JS_BANNER = "/* PromptCraft application bundle. Generated by tools/build.py. */\n"
CSS_BANNER = "/* PromptCraft stylesheet bundle. Generated by tools/build.py. */\n"


def render_js_bundle() -> str:
    chunks = [JS_BANNER]
    for relative_path in JS_SOURCES:
        source = (ROOT / relative_path).read_text(encoding="utf-8").rstrip()
        chunks.append(f"/* SOURCE: {relative_path.as_posix()} */\n")
        chunks.append(source)
        chunks.append("\n;\n")
    return "".join(chunks)


def render_css_bundle() -> str:
    chunks = [CSS_BANNER]
    for relative_path in CSS_SOURCES:
        source = (ROOT / relative_path).read_text(encoding="utf-8").rstrip()
        chunks.append(f"\n/* SOURCE: {relative_path.as_posix()} */\n")
        chunks.append(source)
        chunks.append("\n")
    return "".join(chunks)


def validate_source_manifests() -> list[str]:
    errors: list[str] = []

    declared_js = set(JS_SOURCES) | {source for source, _runtime in JS_STANDALONE_FILES}
    discovered_js = {path.relative_to(ROOT) for path in (ROOT / "src/js").rglob("*.js")}
    unlisted_js = sorted(discovered_js - declared_js)
    missing_js = sorted(declared_js - discovered_js)
    if unlisted_js:
        errors.append(
            "JavaScript source files are not declared in src/js/manifest.json: "
            + ", ".join(path.as_posix() for path in unlisted_js)
        )
    if missing_js:
        errors.append(
            "JavaScript manifest entries are missing from disk: "
            + ", ".join(path.as_posix() for path in missing_js)
        )

    declared_css = set(CSS_SOURCES) | {Path("src/css/pages/ideas-wall.css")}
    discovered_css = {
        path.relative_to(ROOT)
        for path in (ROOT / "src/css").rglob("*.css")
        if path != CSS_MANIFEST_PATH
    }
    unlisted_css = sorted(discovered_css - declared_css)
    missing_css = sorted(declared_css - discovered_css)
    if unlisted_css:
        errors.append(
            "CSS source files are not declared by src/css/manifest.css or standalone ownership: "
            + ", ".join(path.as_posix() for path in unlisted_css)
        )
    if missing_css:
        errors.append(
            "CSS manifest entries are missing from disk: "
            + ", ".join(path.as_posix() for path in missing_css)
        )

    return errors


def run_node_checks() -> list[str]:
    errors: list[str] = []
    paths = [ROOT / path for path in JS_SOURCES]
    paths.extend(
        [
            *(ROOT / source for source, _runtime in JS_STANDALONE_FILES),
            JS_BUNDLE_PATH,
            *(ROOT / runtime for _source, runtime in JS_STANDALONE_FILES),
            ROOT / "netlify/functions/babbage.js",
            ROOT / "tests/test_netlify_function.js",
        ]
    )
    for path in paths:
        if not path.exists():
            errors.append(f"Missing JavaScript file: {path.relative_to(ROOT)}")
            continue
        result = subprocess.run(
            ["node", "--check", str(path)],
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode:
            detail = (result.stderr or result.stdout).strip()
            errors.append(f"JavaScript syntax error in {path.relative_to(ROOT)}: {detail}")
    return errors


def write_if_changed(path: Path, content: str) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else ""
    if current == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def sync_standalone_files(*, check: bool) -> tuple[list[str], list[str]]:
    changed: list[str] = []
    errors: list[str] = []
    for source_rel, runtime_rel in STANDALONE_FILES:
        source_path = ROOT / source_rel
        runtime_path = ROOT / runtime_rel
        source = source_path.read_text(encoding="utf-8")
        current = runtime_path.read_text(encoding="utf-8") if runtime_path.exists() else ""
        if check:
            if current != source:
                errors.append(
                    f"{runtime_rel.as_posix()} is out of date with {source_rel.as_posix()}. Run tools/build.py."
                )
        elif write_if_changed(runtime_path, source):
            changed.append(runtime_rel.as_posix())
    return changed, errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify generated runtime files without writing them.",
    )
    args = parser.parse_args()

    expected_js = render_js_bundle()
    expected_css = render_css_bundle()
    errors = validate_source_manifests()

    if args.check:
        current_js = JS_BUNDLE_PATH.read_text(encoding="utf-8") if JS_BUNDLE_PATH.exists() else ""
        current_css = CSS_BUNDLE_PATH.read_text(encoding="utf-8") if CSS_BUNDLE_PATH.exists() else ""
        if current_js != expected_js:
            errors.append("runtime/js/promptcraft.bundle.js is out of date. Run tools/build.py.")
        if current_css != expected_css:
            errors.append("runtime/css/promptcraft.css is out of date. Run tools/build.py.")
        _changed, sync_errors = sync_standalone_files(check=True)
        errors.extend(sync_errors)
    else:
        js_changed = write_if_changed(JS_BUNDLE_PATH, expected_js)
        css_changed = write_if_changed(CSS_BUNDLE_PATH, expected_css)
        standalone_changed, _sync_errors = sync_standalone_files(check=False)
        print(
            f"JavaScript bundle {'rebuilt' if js_changed else 'already current'} from "
            f"{len(JS_SOURCES)} source modules."
        )
        print(
            f"CSS bundle {'rebuilt' if css_changed else 'already current'} from "
            f"{len(CSS_SOURCES)} owner files."
        )
        if standalone_changed:
            print("Synchronized standalone runtime files: " + ", ".join(standalone_changed))
        else:
            print("Standalone runtime files already current.")

    errors.extend(run_node_checks())
    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1

    print("PromptCraft source and browser runtime files are synchronized.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
