#!/usr/bin/env python3
"""Build and verify PromptCraft's generated JavaScript and CSS bundles.

The browser loads dialogue.js, app.bundle.js, and promptcraft.css. The application
bundle is assembled from the ordered JavaScript source modules below. The stylesheet
bundle is assembled from the ordered CSS owner files listed in style.css.

Edit the modular source files, never the generated bundles, then run this script.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
JS_BUNDLE_PATH = ROOT / "functions" / "app.bundle.js"
CSS_BUNDLE_PATH = ROOT / "styles" / "promptcraft.css"

JS_SOURCES = (
    Path("functions/app.js"),
    Path("functions/app-babbage.js"),
    Path("functions/app-scenario-shared.js"),
    Path("functions/app-scenarios.js"),
    Path("functions/app-scenario-prototypes.js"),
    Path("functions/app-vn.js"),
    Path("functions/app-workbench.js"),
)
CSS_SOURCES = (
    Path("styles/00-base.css"),
    Path("styles/10-visual-novel.css"),
    Path("styles/20-terminal.css"),
    Path("styles/30-legacy-responsive.css"),
    Path("styles/40-components.css"),
    Path("styles/50-layout.css"),
    Path("styles/60-intro-scenes.css"),
    Path("styles/70-prediction-scenes.css"),
    Path("styles/80-live-analysis.css"),
    Path("styles/90-completed-analysis.css"),
    Path("styles/100-scenario-1-workbench.css"),
    Path("styles/110-shared-scenarios.css"),
    Path("styles/115-intro-responsive.css"),
    Path("styles/116-workbench-responsive.css"),
    Path("styles/117-brand-menu.css"),
    Path("styles/118-large-tablet.css"),
    Path("styles/119-prediction-responsive.css"),
)

JS_BANNER = "/* PromptCraft application bundle. Generated by tools/build-production.py. */\n"
CSS_BANNER = "/* PromptCraft stylesheet bundle. Generated by tools/build-production.py. */\n"


def render_js_bundle() -> str:
    chunks = [JS_BANNER]
    for relative_path in JS_SOURCES:
        source = (ROOT / relative_path).read_text(encoding="utf-8").rstrip()
        chunks.append(f"/* SOURCE: {relative_path.as_posix()} */\n")
        chunks.append(source)
        chunks.append("\n;\n")
    return "".join(chunks)


def render_css_bundle() -> str:
    chunks = [CSS_BANNER]
    for relative_path in CSS_SOURCES:
        source = (ROOT / relative_path).read_text(encoding="utf-8").rstrip()
        chunks.append(f"\n/* SOURCE: {relative_path.as_posix()} */\n")
        chunks.append(source)
        chunks.append("\n")
    return "".join(chunks)


def validate_css_manifest() -> list[str]:
    manifest_path = ROOT / "style.css"
    manifest = manifest_path.read_text(encoding="utf-8")
    imports = tuple(
        Path(value)
        for value in re.findall(r'@import\s+url\(["\']([^"\'?]+)', manifest)
    )
    errors: list[str] = []
    if imports != CSS_SOURCES:
        errors.append("style.css import order does not match the CSS owner order.")
    for relative_path in CSS_SOURCES:
        if not (ROOT / relative_path).is_file():
            errors.append(f"Missing CSS source: {relative_path.as_posix()}")
    return errors


def run_node_checks() -> list[str]:
    errors: list[str] = []
    paths = [ROOT / path for path in JS_SOURCES]
    paths.extend(
        [
            ROOT / "functions/dialogue.js",
            ROOT / "functions/wall.js",
            JS_BUNDLE_PATH,
            ROOT / "netlify/functions/babbage.js",
            ROOT / "tools/test-netlify-function.js",
        ]
    )
    for path in paths:
        result = subprocess.run(
            ["node", "--check", str(path)],
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode:
            detail = (result.stderr or result.stdout).strip()
            errors.append(f"JavaScript syntax error in {path.relative_to(ROOT)}: {detail}")
    return errors


def write_if_changed(path: Path, content: str) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else ""
    if current == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify generated bundles and manifests without writing files.",
    )
    args = parser.parse_args()

    expected_js = render_js_bundle()
    expected_css = render_css_bundle()
    errors = validate_css_manifest()

    if args.check:
        current_js = JS_BUNDLE_PATH.read_text(encoding="utf-8") if JS_BUNDLE_PATH.exists() else ""
        current_css = CSS_BUNDLE_PATH.read_text(encoding="utf-8") if CSS_BUNDLE_PATH.exists() else ""
        if current_js != expected_js:
            errors.append("functions/app.bundle.js is out of date. Run tools/build-production.py.")
        if current_css != expected_css:
            errors.append("styles/promptcraft.css is out of date. Run tools/build-production.py.")
    else:
        js_changed = write_if_changed(JS_BUNDLE_PATH, expected_js)
        css_changed = write_if_changed(CSS_BUNDLE_PATH, expected_css)
        print(
            f"JavaScript bundle {'rebuilt' if js_changed else 'already current'} from "
            f"{len(JS_SOURCES)} source modules."
        )
        print(
            f"CSS bundle {'rebuilt' if css_changed else 'already current'} from "
            f"{len(CSS_SOURCES)} owner files."
        )

    errors.extend(run_node_checks())
    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1

    print("PromptCraft production sources are synchronized.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
