#!/usr/bin/env python3
"""Create a reproducible PromptCraft update ZIP from an explicit file manifest."""

from __future__ import annotations

import argparse
import hashlib
import sys
import zipfile
from pathlib import Path, PurePosixPath


ROOT = Path(__file__).resolve().parents[1]
FIXED_ZIP_TIME = (2026, 9, 2, 0, 0, 0)


def read_manifest(path: Path) -> list[str]:
    entries: list[str] = []
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        entry = raw_line.strip()
        if not entry or entry.startswith("#"):
            continue
        entries.append(entry)
    return entries


def validate_entries(root: Path, entries: list[str]) -> list[tuple[str, Path]]:
    if not entries:
        raise ValueError("changed-file manifest is empty")
    if entries != sorted(entries):
        raise ValueError("changed-file manifest must be sorted")
    if len(entries) != len(set(entries)):
        raise ValueError("changed-file manifest contains duplicate paths")

    changed = set(entries)
    validated: list[tuple[str, Path]] = []
    for entry in entries:
        relative = PurePosixPath(entry)
        if relative.is_absolute() or ".." in relative.parts or str(relative) != entry:
            raise ValueError(f"unsafe manifest path: {entry}")
        if relative.name == "desktop.ini" or "__pycache__" in relative.parts:
            raise ValueError(f"generated debris is forbidden: {entry}")
        if relative.suffix in {".pyc", ".pyo"}:
            raise ValueError(f"generated bytecode is forbidden: {entry}")

        source = root.joinpath(*relative.parts)
        if not source.is_file() or source.is_symlink():
            raise ValueError(f"manifest path is not a regular file: {entry}")
        validated.append((entry, source))

    _validate_runtime_ownership(changed)
    return validated


def _validate_runtime_ownership(changed: set[str]) -> None:
    for entry in changed:
        if not entry.startswith("runtime/"):
            continue
        if entry == "runtime/js/promptcraft.bundle.js":
            owned = any(path.startswith("src/js/") and path != "src/js/manifest.json" for path in changed)
        elif entry == "runtime/js/dialogue-data.js":
            owned = "src/js/content/dialogue-data.js" in changed
        elif entry == "runtime/js/ideas-wall.js":
            owned = "src/js/pages/ideas-wall.js" in changed
        elif entry == "runtime/css/promptcraft.css":
            owned = any(
                path.startswith("src/css/") and path != "src/css/pages/ideas-wall.css"
                for path in changed
            )
        elif entry == "runtime/css/ideas-wall.css":
            owned = "src/css/pages/ideas-wall.css" in changed
        else:
            owned = False
        if not owned:
            raise ValueError(f"generated runtime has no changed source owner: {entry}")


def create_zip(output: Path, files: list[tuple[str, Path]]) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for entry, source in files:
            info = zipfile.ZipInfo(entry, date_time=FIXED_ZIP_TIME)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o100644 << 16
            archive.writestr(info, source.read_bytes())


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--root", type=Path, default=ROOT)
    args = parser.parse_args()

    root = args.root.resolve()
    try:
        entries = read_manifest(args.manifest)
        files = validate_entries(root, entries)
        create_zip(args.output, files)
    except (OSError, ValueError, zipfile.BadZipFile) as error:
        print(f"Package failed: {error}", file=sys.stderr)
        return 1

    print(f"Created {args.output} ({len(files)} changed files)")
    print(f"SHA-256 {sha256(args.output)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
