// Canvas-inspired reader and editor checks. Speech fixtures test event timing,
// not audible output or Microsoft Immersive Reader integration.
const {chromium}=require('playwright');
const http=require('http'),fs=require('fs'),path=require('path'),assert=require('assert');
(async()=>{
const server=http.createServer((req,res)=>{const p=path.join(__dirname,'..',new URL(req.url,'http://localhost').pathname);res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.css':'text/css','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml'})[path.extname(p)]||'application/octet-stream');fs.readFile(p,(e,b)=>{res.statusCode=e?404:200;res.end(e?'missing':b);});});await new Promise(r=>server.listen(8766,'127.0.0.1',r));
let browser;
try{for(const [name,w,h] of [['desktop',1440,1000],['short-desktop',1424,720],['tablet',820,1180],['phone',390,844]]){
browser=await chromium.launch({executablePath:process.env.PC_CHROME_EXECUTABLE,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--single-process']});
const page=await browser.newPage({viewport:{width:w,height:h}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());await page.goto('http://127.0.0.1:8766/index.html?mockBabbage=1');await page.waitForTimeout(800);
await page.evaluate(()=>{pcNameConfirmed=pcAudioPreferenceConfirmed=pcScenarioHasLaunched=true;closeMainMenu({force:true});window.pcSpeechFixture={spoken:[],cancels:0,pauses:0,resumes:0};Object.defineProperty(window,'speechSynthesis',{configurable:true,value:{speak:u=>{pcSpeechFixture.spoken.push(u.text);pcSpeechFixture.last=u;u.onstart?.();},cancel:()=>pcSpeechFixture.cancels++,pause:()=>pcSpeechFixture.pauses++,resume:()=>pcSpeechFixture.resumes++}});window.SpeechSynthesisUtterance=function(text){this.text=text;};pcActivateScenario(1,{playIntroduction:false});pcOpenS2AccessPage();});
const capture=async label=>{if(process.env.PC_SCREENSHOTS){fs.mkdirSync(process.env.PC_SCREENSHOTS,{recursive:true});await page.screenshot({path:path.join(process.env.PC_SCREENSHOTS,`${label}-${name}.png`)});}};
const click=async action=>{await page.locator(`[data-pc-action="${action}"]`).last().click();};
await click('s2-reader-toggle');assert(await page.locator('[role="dialog"].pc-s2-immersive').isVisible());assert.strictEqual(await page.evaluate(()=>pcSpeechFixture.spoken.length),0,'No autoplay');
const normal=await page.locator('#pcS2ReaderTranscript').innerText();assert(normal.includes('80 residents'));assert(!normal.includes('Heading level'));assert(normal.includes('Submit your paragraph in Canvas.'));
assert.strictEqual(await page.evaluate(()=>document.activeElement.dataset.pcAction),'s2-reader-close');await page.keyboard.press('Shift+Tab');assert.strictEqual(await page.evaluate(()=>document.activeElement.dataset.pcAction),'s2-reader-after');await page.keyboard.press('Tab');assert.strictEqual(await page.evaluate(()=>document.activeElement.dataset.pcAction),'s2-reader-close');
await click('s2-reader-play');assert.strictEqual(await page.evaluate(()=>pcSpeechFixture.last.rate),1.25);
await page.evaluate(()=>pcSpeechFixture.last.onboundary({charIndex:10,name:'word'}));assert.strictEqual(await page.locator('.is-current-word').innerText(),'a');assert.strictEqual(await page.locator('.is-current-passage').count(),1);await capture('reader-word');
await click('s2-reader-play');assert.strictEqual(await page.evaluate(()=>pcSpeechFixture.pauses),1);assert((await page.locator('[data-pc-action="s2-reader-play"]').innerText()).includes('Resume'));await click('s2-reader-play');
await page.selectOption('#pcS2ReaderRate','2');assert.strictEqual(await page.evaluate(()=>pcSpeechFixture.last.rate),2);assert((await page.evaluate(()=>pcSpeechFixture.last.text)).startsWith('a community'));
await click('s2-reader-play');await page.selectOption('#pcS2ReaderRate','1.5');assert.strictEqual(await page.evaluate(()=>pcS2ReaderPlayback.paused),true);assert.strictEqual(await page.evaluate(()=>pcSpeechFixture.last.rate),1.5);await click('s2-reader-play');
await page.selectOption('[data-pc-change-action="s2-reader-size"]','30');assert.strictEqual(await page.locator('#pcS2ReaderTranscript').evaluate(el=>getComputedStyle(el).fontSize),'30px');await page.uncheck('[data-pc-change-action="s2-reader-spacing"]');assert(!(await page.locator('#pcS2ReaderPanel').getAttribute('class')).includes('has-spacing'));
await click('s2-reader-before');assert((await page.locator('#pcS2ReaderTranscript').innerText()).includes('No more headings'));assert(!(await page.locator('#pcS2ReaderTranscript').innerText()).includes('Heading level 2'));await page.evaluate(()=>pcSpeechFixture.last.onend());assert((await page.evaluate(()=>pcSpeechFixture.last.text)).includes('No more headings'));assert((await page.locator('.is-current-passage').innerText()).includes('No more headings'));
await click('s2-reader-after');assert((await page.locator('#pcS2ReaderTranscript').innerText()).includes('Heading level 3. Before you submit.'));for(let i=0;i<5;i++)await page.evaluate(()=>pcSpeechFixture.last.onend());assert(await page.locator('[data-pc-action="s2-reader-stop"]').isDisabled());
await click('s2-reader-play');await page.evaluate(()=>window.pcOldSpeechEnd=pcSpeechFixture.last.onend);await click('s2-reader-stop');assert.strictEqual(await page.evaluate(()=>pcS2ReaderPlayback),null);await page.evaluate(()=>pcOldSpeechEnd());assert.strictEqual(await page.evaluate(()=>pcS2ReaderPlayback),null);
await click('s2-reader-read');await page.evaluate(()=>pcSpeechFixture.last.onerror());assert((await page.locator('#pcS2ReaderStatus').innerText()).includes('could not play'));
await page.evaluate(()=>Object.defineProperty(window,'speechSynthesis',{configurable:true,value:null}));await click('s2-reader-play');assert((await page.locator('#pcS2ReaderStatus').innerText()).includes('unavailable'));assert((await page.locator('#pcS2ReaderTranscript').innerText()).includes('80 residents'));
await page.keyboard.press('Escape');assert.strictEqual(await page.locator('#pcS2ReaderPanel').count(),0);assert.strictEqual(await page.evaluate(()=>document.activeElement.dataset.pcAction),'s2-reader-toggle');assert.strictEqual(await page.evaluate(()=>document.getElementById('chat').inert),false);
await page.evaluate(()=>Object.defineProperty(window,'speechSynthesis',{configurable:true,value:{speak:u=>{pcSpeechFixture.last=u;u.onstart?.();},cancel:()=>pcSpeechFixture.cancels++,pause:()=>{},resume:()=>{}}}));
await click('s2-reader-toggle');await click('s2-reader-play');await page.evaluate(()=>openMainMenu());await page.waitForTimeout(30);assert.strictEqual(await page.evaluate(()=>pcS2ReaderView),null);assert.strictEqual(await page.evaluate(()=>pcS2ReaderPlayback),null);assert.strictEqual(await page.evaluate(()=>document.getElementById('mainMenuOverlay').inert),false);await page.evaluate(()=>closeMainMenu({force:true}));
await click('s2-reader-toggle');await click('s2-reader-play');await page.evaluate(()=>pcActivateScenario(0,{playIntroduction:false}));await page.waitForTimeout(50);assert.strictEqual(await page.evaluate(()=>pcS2ReaderView),null);assert.strictEqual(await page.evaluate(()=>pcS2ReaderPlayback),null);
// Practice the actual footer toggle and heading dropdown with unchanged wording.
await page.evaluate(()=>{pcActivateScenario(1,{playIntroduction:false});pcS2AccessState.draft=pcS2HeadingExample();pcS2AccessState.pasted=PC_S2_PAGE_HTML;pcS2AccessState.view='paste';pcRenderS2AccessScreen();});
assert(await page.locator('.pc-s2-rce-visual').isVisible());assert(!(await page.locator('#pcS2PastedHtml').isVisible()));
await page.locator('[data-pc-heading="What you will learn"]').click();await page.selectOption('#pcS2HeadingStyle','h2');assert((await page.evaluate(()=>pcS2AccessState.pasted)).includes('<h2>What you will learn</h2>'));assert((await page.locator('.pc-s2-rce-visual').innerText()).includes('80 residents'));
await capture('editor-visual');await click('s2-editor-toggle-html');assert(await page.locator('#pcS2PastedHtml').isVisible());assert.strictEqual(await page.evaluate(()=>document.activeElement.id),'pcS2PastedHtml');
await page.fill('#pcS2PastedHtml','<img src=x onerror="window.pcUnsafeHTML=true">');await click('s2-editor-toggle-html');assert.strictEqual(await page.evaluate(()=>window.pcUnsafeHTML),undefined);assert.strictEqual(await page.locator('.pc-s2-rce-visual img').count(),0);
await click('s2-access-insert');assert((await page.locator('#pcS2PastedHtml').inputValue()).includes('<h2>'));await capture('editor-html');await click('s2-editor-toggle-html');assert(await page.locator('.pc-s2-rce-visual h2').count()===3);await click('s2-access-preview-repair');assert(await page.locator('.pc-s2-access-checks').isVisible());await click('s2-reader-toggle');assert((await page.locator('#pcS2ReaderTranscript').innerText()).includes('80 residents'));await click('s2-reader-close');
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);assert(!overflow);assert.deepStrictEqual(errors,[]);console.log(name,'PASS: reader words/passages, speed, pause/resume, focus restoration, end/error/fallback, menu/scenario cleanup; Canvas styles/HTML toggle/safe preview.');await browser.close();
}}finally{await browser?.close();server.close();}
})().catch(e=>{console.error(e);process.exit(1)});
